# Generated by Django 4.2.4 on 2026-01-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('in_use', models.BooleanField(default=True)),
                ('pfand', models.BooleanField(default=True)),
                ('summer_product', models.BooleanField(default=True)),
                ('winter_product', models.BooleanField(default=True)),
                ('bar_product', models.BooleanField(default=True)),
                ('kitchen_product', models.BooleanField(default=True)),
                ('price_default', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_sgle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_dble', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_dash', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_03', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_04', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_pint', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_btle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_small', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_jumbo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_2.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_2.subcategory')),
            ],
        ),
    ]
