# Generated by Django 4.2.4 on 2026-02-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0003_productv2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfand', models.DecimalField(decimal_places=2, max_digits=5)),
                ('default_drink_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_2.drinksizes')),
                ('default_food_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_2.foodsizes')),
            ],
        ),
    ]
