# Generated by Django 4.2.4 on 2026-02-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0004_drinksizes_foodsizes_miscellaneoussettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinksizes',
            options={'verbose_name_plural': 'Drink Sizes'},
        ),
        migrations.AlterModelOptions(
            name='foodsizes',
            options={'verbose_name_plural': 'Food Sizes'},
        ),
        migrations.AlterModelOptions(
            name='miscellaneoussettings',
            options={'verbose_name_plural': 'Miscellaneous Settings'},
        ),
        migrations.RenameField(
            model_name='productv2',
            old_name='price_btle',
            new_name='price_bottle',
        ),
        migrations.RenameField(
            model_name='productv2',
            old_name='price_dble',
            new_name='price_double',
        ),
        migrations.RenameField(
            model_name='productv2',
            old_name='price_jumbo',
            new_name='price_large',
        ),
        migrations.RenameField(
            model_name='productv2',
            old_name='price_sgle',
            new_name='price_single',
        ),
    ]
