# Generated by Django 4.2.4 on 2026-02-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0005_alter_drinksizes_options_alter_foodsizes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplimentaryReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Complimentary Reasons',
            },
        ),
        migrations.CreateModel(
            name='WasteReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Waste Reasons',
            },
        ),
    ]
