# Generated by Django 4.2.4 on 2026-02-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_grandtotal_discounts'),
        ('version_2', '0006_complimentaryreasons_wastereasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandTotalV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('number_of_products', models.IntegerField(blank=True, null=True)),
                ('pfand_buttons_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('drinks_food_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pfand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_due', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tendered_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('change_due', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('discounts', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PfandBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glasses_out', models.IntegerField(blank=True, null=True)),
                ('pfand_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItemV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_li', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_2.category')),
                ('grand_totals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_2.grandtotalv2')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.staff')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_2.subcategory')),
            ],
        ),
    ]
