# Generated by Django 4.2.4 on 2026-02-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0007_grandtotalv2_pfandbalance_lineitemv2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pfandbalance',
            old_name='glasses_out',
            new_name='glasses_balance',
        ),
        migrations.RenameField(
            model_name='pfandbalance',
            old_name='pfand_in',
            new_name='pfand_balance',
        ),
    ]
