# Generated by Django 4.2.4 on 2026-02-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0008_rename_glasses_out_pfandbalance_glasses_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfandbalance',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
