# Generated by Django 4.2.4 on 2026-02-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0009_pfandbalance_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfandbalance',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
