# Generated by Django 4.2.4 on 2026-03-02 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0010_alter_pfandbalance_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitemv2',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='lineitemv2',
            name='payment_reason',
        ),
        migrations.RemoveField(
            model_name='lineitemv2',
            name='staff_member',
        ),
        migrations.AddField(
            model_name='grandtotalv2',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
