# Generated by Django 4.2.4 on 2026-03-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0011_remove_lineitemv2_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grandtotalv2',
            name='order_number',
        ),
    ]
