# Generated by Django 4.2.4 on 2026-03-02 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0012_remove_grandtotalv2_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandtotalv2',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
