# Generated by Django 4.2.4 on 2026-03-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0013_grandtotalv2_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grandtotalv2',
            old_name='order_number',
            new_name='transaction_number',
        ),
    ]
