# Generated by Django 4.2.4 on 2026-03-04 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0014_rename_order_number_grandtotalv2_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandtotalv2',
            name='transaction_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
