# Generated by Django 4.2.4 on 2026-03-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0016_alter_grandtotalv2_transaction_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitemv2',
            old_name='order_date_li',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='lineitemv2',
            old_name='grand_totals',
            new_name='transaction',
        ),
    ]
