# Generated by Django 4.2.4 on 2026-03-04 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0017_rename_order_date_li_lineitemv2_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandtotalv2',
            name='transaction_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
