# Generated by Django 4.2.4 on 2026-03-04 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0018_alter_grandtotalv2_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandtotalv2',
            name='transaction_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
