# Generated by Django 4.2.4 on 2026-03-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0019_alter_grandtotalv2_transaction_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitemv2',
            name='order_date',
        ),
    ]
