# Generated by Django 4.2.4 on 2026-03-05 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0020_remove_lineitemv2_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandtotalv2',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
