# Generated by Django 4.2.4 on 2026-04-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0022_testcategory_alter_lineitemv2_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_2.category')),
            ],
            options={
                'verbose_name_plural': 'Product Sizes',
            },
        ),
    ]
