# Generated by Django 4.2.4 on 2026-04-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0023_productsizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='default_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_2.productsizes'),
        ),
    ]
