# Generated by Django 4.2.4 on 2026-04-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0024_subcategory_default_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='miscellaneoussettings',
            name='default_drink_size',
        ),
        migrations.RemoveField(
            model_name='miscellaneoussettings',
            name='default_food_size',
        ),
        migrations.AlterField(
            model_name='productsizes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_2.category'),
        ),
        migrations.DeleteModel(
            name='DrinkSizes',
        ),
        migrations.DeleteModel(
            name='FoodSizes',
        ),
        migrations.DeleteModel(
            name='MiscellaneousSettings',
        ),
    ]
