# Generated by Django 4.2.4 on 2026-04-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0025_subsubcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productv2',
            old_name='price_default',
            new_name='price_no_size',
        ),
        migrations.AddField(
            model_name='productv2',
            name='cloth_2xl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productv2',
            name='cloth_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productv2',
            name='cloth_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productv2',
            name='cloth_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productv2',
            name='cloth_xl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productv2',
            name='cloth_xs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productv2',
            name='gift_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productv2',
            name='position_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productv2',
            name='subsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_2.subsubcategory'),
        ),
    ]
