# Generated by Django 4.2.4 on 2026-04-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0026_rename_price_default_productv2_price_no_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='default_size',
        ),
        migrations.AddField(
            model_name='productv2',
            name='default_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_2.productsizes'),
        ),
    ]
