# Generated by Django 4.2.4 on 2026-05-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0030_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandtotalv2',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_2.events'),
        ),
    ]
