# Generated by Django 4.2.4 on 2026-05-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0031_grandtotalv2_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='complimentaryreasons',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsizes',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wastereasons',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
    ]
