# Generated by Django 4.2.4 on 2026-05-25 13:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0032_complimentaryreasons_in_use_productsizes_in_use_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='EndOfDayTakings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trading_date', models.DateField()),
                ('one_cent', models.IntegerField(default=0)),
                ('one_cent_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('two_cent', models.IntegerField(default=0)),
                ('two_cent_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('five_cent', models.IntegerField(default=0)),
                ('five_cent_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ten_cent', models.IntegerField(default=0)),
                ('ten_cent_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('twenty_cent', models.IntegerField(default=0)),
                ('twenty_cent_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fifty_cent', models.IntegerField(default=0)),
                ('fifty_cent_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('one_euro', models.IntegerField(default=0)),
                ('one_euro_value', models.IntegerField(default=0)),
                ('two_euro', models.IntegerField(default=0)),
                ('two_euro_value', models.IntegerField(default=0)),
                ('five_euro', models.IntegerField(default=0)),
                ('five_euro_value', models.IntegerField(default=0)),
                ('ten_euro', models.IntegerField(default=0)),
                ('ten_euro_value', models.IntegerField(default=0)),
                ('twenty_euro', models.IntegerField(default=0)),
                ('twenty_euro_value', models.IntegerField(default=0)),
                ('fifty_euro', models.IntegerField(default=0)),
                ('fifty_euro_value', models.IntegerField(default=0)),
                ('one_hundred_euro', models.IntegerField(default=0)),
                ('one_hundred_euro_value', models.IntegerField(default=0)),
                ('two_hundred_euro', models.IntegerField(default=0)),
                ('two_hundred_euro_value', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('two_for_one_vouchers', models.IntegerField(default=0)),
                ('ten_for_eleven_vouchers', models.IntegerField(default=0)),
                ('customer_20_off_vouchers', models.IntegerField(default=0)),
                ('austeller_20_off_vouchers', models.IntegerField(default=0)),
                ('student_discount_vouchers', models.IntegerField(default=0)),
                ('oap_discount_vouchers', models.IntegerField(default=0)),
                ('five_euro_off_vouchers', models.IntegerField(default=0)),
                ('receipts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_2.receipts')),
            ],
        ),
    ]
