# Generated by Django 4.2.4 on 2026-05-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_grandtotal_discounts'),
        ('version_2', '0033_receipts_endofdaytakings'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofdaytakings',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.staff'),
        ),
    ]
