# Generated by Django 4.2.4 on 2026-05-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0034_endofdaytakings_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofdaytakings',
            name='fifty_cent_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='fifty_euro_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='five_cent_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='five_euro_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='one_cent_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='one_euro_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='one_hundred_euro_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='ten_cent_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='ten_euro_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='twenty_cent_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='twenty_euro_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='two_cent_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='two_euro_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endofdaytakings',
            name='two_hundred_euro_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
