# Generated by Django 4.2.4 on 2026-05-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0035_alter_endofdaytakings_fifty_cent_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
