# Generated by Django 4.2.4 on 2026-05-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0036_receipts_image_alter_receipts_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
