# Generated by Django 4.2.4 on 2026-05-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0037_alter_receipts_name_alter_receipts_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofdaytakings',
            name='receipts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='version_2.receipts'),
        ),
    ]
