# Generated by Django 4.2.4 on 2026-05-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_grandtotal_discounts'),
        ('version_2', '0038_alter_endofdaytakings_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofdaytakings',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.staff'),
        ),
    ]
