# Generated by Django 4.2.4 on 2026-06-01 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0039_alter_endofdaytakings_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofdaytakings',
            name='receipts',
        ),
        migrations.AddField(
            model_name='receipts',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
