# Generated by Django 4.2.4 on 2026-06-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_grandtotal_discounts'),
        ('version_2', '0040_remove_endofdaytakings_receipts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofdaytakings',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='version_2.events'),
        ),
        migrations.AddField(
            model_name='receipts',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='version_2.events'),
        ),
        migrations.AddField(
            model_name='receipts',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.staff'),
        ),
    ]
