# Generated by Django 4.2.4 on 2026-06-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0041_endofdaytakings_event_receipts_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
