# Generated by Django 4.2.4 on 2026-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0042_receipts_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productv2',
            name='cloth_3xl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
