# Generated by Django 4.2.4 on 2026-07-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0043_productv2_cloth_3xl'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemv2',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_2.productv2'),
        ),
    ]
