# Generated by Django 4.2.4 on 2026-07-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0044_lineitemv2_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitemv2',
            old_name='product_id',
            new_name='productId',
        ),
    ]
