# Generated by Django 4.2.4 on 2026-07-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0045_rename_product_id_lineitemv2_productid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitemv2',
            old_name='productId',
            new_name='product',
        ),
    ]
