# Generated by Django 4.2.4 on 2026-07-21 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0046_rename_productid_lineitemv2_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemv2',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineitems_v2', to='version_2.productv2'),
        ),
    ]
