# Generated by Django 4.2.4 on 2026-07-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0047_alter_lineitemv2_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitemv2',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lineitemv2',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='lineitemv2',
            name='subsubcategory',
        ),
    ]
