# Generated by Django 4.2.4 on 2026-07-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_2', '0048_remove_lineitemv2_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizes',
            name='ml_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
