# Generated by Django 4.2.4 on 2023-10-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_canandbottle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price_single', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_double', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_bottle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
