# Generated by Django 4.2.4 on 2023-10-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_spirit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price_dash', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_03', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_04', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_pint', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_bottle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
