# Generated by Django 4.2.4 on 2023-10-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotalcoholic',
            old_name='price_regular',
            new_name='price_default',
        ),
        migrations.RenameField(
            model_name='hotnonalcoholic',
            old_name='price_regular',
            new_name='price_default',
        ),
        migrations.RenameField(
            model_name='hottoddy',
            old_name='price_regular',
            new_name='price_default',
        ),
        migrations.RenameField(
            model_name='shot',
            old_name='price_regular',
            new_name='price_default',
        ),
        migrations.AddField(
            model_name='canandbottle',
            name='price_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='draught',
            name='price_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='halfandhalf',
            name='price_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shandy',
            name='price_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='softdrink',
            name='price_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='spirit',
            name='price_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
