# Generated by Django 4.2.4 on 2023-10-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_rename_price_regular_hotalcoholic_price_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products', models.IntegerField(blank=True, null=True)),
                ('drinks_food_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pfand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_due', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tendered_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('change_due', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price_default', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_dash', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_03', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_04', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_pint', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_bottle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_330', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_440', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_small', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grand_totals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.grandtotal')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.product')),
            ],
        ),
    ]
