# Generated by Django 4.2.4 on 2023-10-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_grandtotal_product_lineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_double',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
