# Generated by Django 4.2.4 on 2023-10-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_product_price_double'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandtotal',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
