# Generated by Django 4.2.4 on 2023-10-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_delete_canandbottle_delete_draught_delete_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grandtotal',
            old_name='payment_category',
            new_name='payment_reason',
        ),
    ]
