# Generated by Django 4.2.4 on 2023-11-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_rename_payment_category_grandtotal_payment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
