# Generated by Django 4.2.4 on 2023-11-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_lineitem_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='order_date',
            new_name='order_date_li',
        ),
    ]
