# Generated by Django 4.2.4 on 2023-11-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_grandtotal_pfand_buttons_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
