# Generated by Django 4.2.4 on 2023-12-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_lineitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pfand',
            field=models.BooleanField(default=True),
        ),
    ]
