# Generated by Django 4.2.4 on 2024-03-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_rename_price_330_product_price_single_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_bottle',
            new_name='price_btle',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_double',
            new_name='price_dble',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_single',
            new_name='price_sgle',
        ),
    ]
