# Generated by Django 4.2.4 on 2024-03-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_rename_price_bottle_product_price_btle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandtotal',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.staff'),
        ),
    ]
