# Generated by Django 4.2.4 on 2024-06-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_grandtotal_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='payment_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
    ]
