# Generated by Django 4.2.4 on 2024-06-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_alter_lineitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.staff'),
        ),
    ]
