# Generated by Django 4.2.4 on 2024-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_lineitem_staff_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
