# Generated by Django 4.2.4 on 2024-06-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_alter_lineitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bar_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kitchen_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summer_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='winter_product',
            field=models.BooleanField(default=True),
        ),
    ]
