# Generated by Django 4.2.4 on 2024-06-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_product_bar_product_product_kitchen_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='abbr_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
