# Generated by Django 4.2.4 on 2024-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_product_abbr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_jumbo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
